import React, { useState } from "react";
import { Head, router, useForm } from "@inertiajs/react";
import { Edit2, Package, Plus, Search, Trash2, X } from "lucide-react";
import SumberPvcLayout from "@/Layouts/SumberPvcLayout";

type Item = { id:number; kode_barang:string; nama_barang:string; kategori:"Tali Jepit"|"Outsole"|"Boloni Gunung"; jenis:string|null; warna:string|null; stok_minimum:number; stok_saat_ini:number; keterangan:string|null };
type Props = { items:{data:Item[]; links:any[]; total:number}; filters:{search?:string} };
const blank = { nama_barang:"", kode_barang:"", kategori:"Tali Jepit" as Item["kategori"], jenis:"", warna:"", stok_minimum:25, stok_saat_ini:0, keterangan:"" };

export default function Master({items, filters}:Props) {
  const [search,setSearch]=useState(filters.search||""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Item|null>(null);
  const {data,setData,post,put,delete:destroy,reset,processing,errors}=useForm(blank);
  const isOutsole=data.kategori==="Outsole", isBoloni=data.kategori==="Boloni Gunung";
  const openCreate=()=>{setEditing(null);reset();setOpen(true)};
  const openEdit=(item:Item)=>{setEditing(item);setData({nama_barang:item.nama_barang,kode_barang:item.kode_barang,kategori:item.kategori,jenis:item.jenis||"",warna:item.warna||"",stok_minimum:item.stok_minimum,stok_saat_ini:item.stok_saat_ini,keterangan:item.keterangan||""});setOpen(true)};
  const submit=(event:React.FormEvent)=>{event.preventDefault(); const done=()=>{setOpen(false);reset()}; editing?put(route("admin.master-products.update",editing.id),{onSuccess:done}):post(route("admin.master-products.store"),{onSuccess:done})};
  const changeCategory=(kategori:Item["kategori"])=>setData({...data,kategori,jenis:kategori==="Boloni Gunung"?"":data.jenis,warna:kategori==="Outsole"?"":data.warna});
  return <SumberPvcLayout><Head title="Master Produk" />
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold text-slate-800"><Package size={21} className="text-blue-600"/>Master Produk</h1><p className="mt-1 text-xs text-slate-400">Atur kategori, jenis, warna, kode, dan batas stok produk jadi.</p></div><button onClick={openCreate} className="inline-flex items-center gap-2 self-start rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white"><Plus size={14}/>Tambah Master Produk</button></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form onSubmit={event=>{event.preventDefault();router.get(route("admin.master-products"),{search},{preserveState:true})}} className="relative max-w-sm"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Cari kategori, jenis, atau warna..." className="w-full rounded-lg border-slate-200 py-2 pl-9 text-xs"/></form></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-400"><tr><th className="p-4">Kode</th><th className="p-4">Kategori</th><th className="p-4">Jenis</th><th className="p-4">Warna</th><th className="p-4">Stok Minimum</th><th className="p-4">Stok Awal/Saat Ini</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{items.data.map(item=><tr key={item.id}><td className="p-4 font-mono font-bold text-slate-600">{item.kode_barang}</td><td className="p-4">{item.kategori}</td><td className="p-4 font-semibold">{item.jenis||"—"}</td><td className="p-4">{item.warna||"—"}</td><td className="p-4">{item.stok_minimum} kodi</td><td className="p-4 font-bold text-blue-700">{item.stok_saat_ini} kodi</td><td className="p-4 text-right"><button onClick={()=>openEdit(item)} className="p-1.5 text-blue-600"><Edit2 size={14}/></button><button onClick={()=>confirm(`Hapus ${item.nama_barang}?`)&&destroy(route("admin.master-products.destroy",item.id))} className="p-1.5 text-red-500"><Trash2 size={14}/></button></td></tr>)}{items.data.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-400">Belum ada master produk.</td></tr>}</tbody></table></div></div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-slate-900/40" onClick={()=>setOpen(false)}/><form onSubmit={submit} className="relative w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">{editing?"Ubah Master Produk":"Tambah Master Produk"}</h2><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Nama produk" value={data.nama_barang} onChange={value=>setData("nama_barang",value)}/><Field label="Kode barang" value={data.kode_barang} onChange={value=>setData("kode_barang",value)}/><label className="text-[10px] font-bold uppercase text-slate-400">Kategori<select value={data.kategori} onChange={event=>changeCategory(event.target.value as Item["kategori"])} className="mt-1 block w-full rounded-lg border-slate-200 py-2 text-xs"><option>Tali Jepit</option><option>Outsole</option><option>Boloni Gunung</option></select></label>{!isBoloni&&<Field label={isOutsole?"Jenis outsole":"Jenis tali jepit"} value={data.jenis} onChange={value=>setData("jenis",value)}/>} {!isOutsole&&<Field label="Warna" value={data.warna} onChange={value=>setData("warna",value)}/>}<Field label="Stok minimum (kodi)" type="number" value={data.stok_minimum} onChange={value=>setData("stok_minimum",Number(value))}/>{!editing&&<Field label="Stok awal (kodi)" type="number" value={data.stok_saat_ini} onChange={value=>setData("stok_saat_ini",Number(value))}/>}</div><Field label="Keterangan" value={data.keterangan} onChange={value=>setData("keterangan",value)}/>{Object.values(errors).map(error=><p key={error} className="text-xs text-red-600">{error}</p>)}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2 text-xs font-bold">Batal</button><button disabled={processing} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">Simpan</button></div></form></div>}
  </SumberPvcLayout>
}
function Field({label,value,onChange,type="text"}:{label:string;value:string|number;onChange:(value:string)=>void;type?:string}){return <label className="text-[10px] font-bold uppercase text-slate-400">{label}<input required type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 block w-full rounded-lg border-slate-200 py-2 text-xs font-semibold normal-case text-slate-700"/></label>}
